version: '2'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: 'spoc'
      MYSQL_SCHEMA: 'spoc'
      MYSQL_USER: 'spoc'
      MYSQL_PASSWORD: 'spoc'
    ports:
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - todo-mysql-data:/var/lib/mysql
  spoc-backend:
    image: 'cmh1506/spoc:latest'
    build:
      context: src/main/docker
    container_name: spoc-backend
    ports:
      - "8080:8080"
    links:
      - "db"
    depends_on:
      - db
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: spoc
      MYSQL_PASSWORD: spoc
      MYSQL_DB: spoc
  spoc-frontend:
    image: 'cmh1506/spoc_frontend:latest'
    container_name: spoc-frontend
    links:
      - "spoc-backend"
    depends_on:
      - "spoc-backend"
    ports:
      - "80:80"
volumes:
  todo-mysql-data:

